### ISSUE TITLE
Hello! 

### ISSUE THREAD

**Issue by 001bl33d** [Neoncat-OG/TrollStore-IPAs#2]
hope all is doing u well u say u need help well i have a few suggestions and i may add that im more than willing to help if we can come to an agreement since the last one got taken down by github it’s only a matter of time before e they’ll just do it to this one and we lose all access so i suggest we use this as a base to get everyone on board and we start something like a telegram or a discord where we can release when we are able to (free time, etc) i have a few friends in on the project with me i was originally going to do that until i seen your repo.. hope all goes well and thanks for providing for the sideloading community

**Comment by Neoncat-OG** [comment]
I would be happy to work together and a agree with the fact that GitHub isn’t the best place to do this on but the whole point of the project is to have a repo that one can simply import into a signing app. So I could modify the GitHub to upload the files to catbox to maybe prevent the DMCAs. If you know of another solution please let me know.

**Comment by Tgod1991** [comment]
Could we make a discord server for those (myself) who don't have telegram. And share there. I love the ease of GitHub but DMCA will be inevitable with the more popular this becomes unfortunately. If I can be of any help, I would love to. 😎🫡

**Comment by Neoncat-OG** [comment]
@Tgod1991 @001bl33d A discord where we would release the ipas along with a repo, sounds great. If you would like to start, you could reach out to me at clinthitem@gmail.com. Thanks for offering your help.
